export const myNavCards = [
    {
      id: 1,
      title: "Adventures",
      description: "An assortment of random pictures from my daily life.(Work in Progress)",
      image: "RiCompass3Fill",
      navTo:"adventures",
    },
    {
      id: 2,
      title: "Budgets",
      description: "Make a budget and see where you can save money for savings.(Work in Progress)",
      image: "RiCopperDiamondFill",
      navTo:"budgets",
    },
    {
      id: 3,
      title: "Gaming Adventures",
      description: "Collection of screenshots from my adventures in games.(Work in Progress)",
      image: "RiGlobeLine",
      navTo:"gamingadventures",
    },
    {
      id: 4,
      title: "Habit Tracker",
      description: "A habit tracker to make your life better- one day at a time.(Work in Progress)",
      image: "RiHazeLine",
      navTo:"habits",
    },
    {
      id: 5,
      title: "My Personal App!",
      description: "Welcome to my app. I am a Software Engineer who enjoys helping people solve problems with code when they need it.",
      image: "RiTreasureMapLine",
      navTo:"",
    },
    {
      id: 6,
      title: "My Projects",
      description: "Here is a collection of my personal projects.(Work in Progress)",
      image: "RiSpaceShipLine",
      navTo:"projects", 
    },
    {
      id: 7,
      title: "Purchase Goals",
      description: "Here you can calculate how to afford that big purchase you've been dieing to make based on your input.(Work in Progress)",
      image: "RiStore3Fill",
      navTo:"purchasegoals", 
    },
    {
      id: 8,
      title: "Recipe List",
      description: "Here you can see a list of recipes.(Work in Progress)",
      image: "RiRestaurant2Fill",
      navTo:"recipes", 
    },
    {
      id: 9,
      title: "My Skills",
      description: "Here you can view my current skills along with the ones I am currently working on.(Work in Progress)",
      image: "RiShieldUserLine",
      navTo:"skills",

    },
  ]