export const myNavCards = [
    {
      id: 1,
      title: "Adventures",
      description: "An assortment of random pictures from my daily life.",
      image: "RiCompass3Fill",
      navTo:"adventures",
    },
    {
      id: 2,
      title: "Budgets",
      description: "Make a budget and see where you can save money for savings.(Work in Progress)",
      image: "RiCopperDiamondFill",
      navTo:"budgets",
    },
    {
      id: 3,
      title: "Hobbies",
      description: "Collection of pictures from my various hobbies.",
      image: "RiGlobeLine",
      navTo:"hobbies",
    },
    {
      id: 4,
      title: "Habit Tracker",
      description: "A habit tracker to make your life better- one day at a time.(Work in Progress)",
      image: "RiHazeLine",
      navTo:"habits",
    },
    {
      id: 5,
      title: "My Personal App!",
      description: "Welcome to my app. I am a Software Engineer who enjoys helping people solve problems with code when they need it.",
      image: "RiTreasureMapLine",
      navTo:"",
    },
    {
      id: 6,
      title: "My Projects",
      description: "Here is a collection of my personal projects.",
      image: "RiSpaceShipLine",
      navTo:"projects", 
    },
    {
      id: 7,
      title: "Purchase Goals",
      description: "Here you can calculate how to afford that big purchase you've been dieing to make based on your input.(Work in Progress)",
      image: "RiStore3Fill",
      navTo:"purchasegoals", 
    },
    {
      id: 8,
      title: "Recipe List",
      description: "Here you can see a list of recipes.(Work in Progress)",
      image: "RiRestaurant2Fill",
      navTo:"recipes", 
    },
    {
      id: 9,
      title: "My Skills",
      description: "Here you can view my current skills along with the ones I am currently working on.",
      image: "RiShieldUserLine",
      navTo:"skills",

    },
  ]

export const myGamingAdventures = [
  {
    id: 1,
    title: "Ironton",
    description: "Our newest resource gathering base.",
    image: "./assets/ironton.jpg",
  },
  {
    id: 2,
    title: "Portal Room",
    description: "Current iteration of our main portal room.",
    image: "./assets/portal_room.jpg",
  },
  {
    id: 3,
    title: "Royal Harbor",
    description: "Our royal harbor that is still being created.",
    image: "./assets/capital_harbor.jpg",
  },
  {
    id: 4,
    title: "Meadhall",
    description: "Our most recent version of our main meadhall.",
    image: "./assets/capital_meadhall.jpg",
  },
  {
    id: 5,
    title: "Capital Center",
    description: "The center of our capital.",
    image: "./assets/capital_center.jpg",
  },
  {
    id: 6,
    title: "Capital Farm",
    description: "Our major farm for rich ingredients.",
    image: "./assets/capital_farm.jpg",
  },
  {
      id: 7,
      title: "Pvp Base",
      description: "My first major iteration of my base on our private server.",
      image: "./assets/pvp_base.png",
    },
    {
      id: 8,
      title: "Copper Deposit",
      description: "What a copper deposit looks like!",
      image: "./assets/copper_deposit.jpg",
    },
    {
      id: 9,
      title: "Tin Deposit",
      description: "What a tin deposit looks like!",
      image: "./assets/tin_deposit.jpg",
    },
    {
      id: 10,
      title: "Ruins",
      description: "A run-down ruin in the Black Forest!",
      image: "./assets/black_forest_ruins.jpg",
    },
    {
      id: 11,
      title: "Dungeon",
      description: "An underground dungeon in the Black Forest!",
      image: "./assets/black_forest_dungeon_underground.jpg", 
    },
    {
      id: 12,
      title: "Monolith",
      description: "A monolith in the Plains!",
      image: "./assets/plains_monolith.jpg",
    },
    {
      id: 13,
      title: "Depths",
      description: "The depths of a cave system close to the core of the planet.",
      image: "./assets/depths.jpg",
    },
    {
      id: 14,
      title: "Mysterious Object",
      description: "A mysterious object that teleports and changes patterns when interacted with.",
      image: "./assets/mysterious_object.jpg",
    },
    {
      id: 15,
      title: "Giant Mushrooms",
      description: "Giant mushrooms found closer to the center of this planet.",
      image: "./assets/giant_mushrooms.jpg",
    },
  ]

  export const myAdventures = [
    {
        id: 1,
        title: "Three Bunnies",
        description: "The three bunnies I see wandering around every morning.",
        image: "./assets/three_bunnies.jpeg",
      },
      {
        id: 2,
        title: "Computer Parts",
        description: "What my first self built computer looked like before we finished.",
        image: "./assets/computer_before.jpeg",
      },
      {
        id: 3,
        title: "Finished First Build",
        description: "What my first self built computer looked like when we finished.",
        image: "./assets/computer_after.jpeg",
      },
]

export const myRecipes = [
  {
    id: 1,
    title: "Meatball Sub",
    description: "A delicious meatball sub.",
    ingredients: ["Meatballs", "Cheese", "Sub Rolls"],
  },
  {
    id: 2,
    title: "Cheeseburger",
    description: "Tasty cheese burger.",
    ingredients: ["Buns", "Patty", "Cheese"],
  },
  {
    id: 3,
    title: "Chicken Broccoli Alfredo",
    description: "A fantastic pasta dish.",
    ingredients: ["Pasta","Broccoli","Chicken", "Heavy Cream", "Minced Garlic", "Grated Parmesan Cheese", "Nutmeg", "Black Pepper", "Salt", "Butter"],
  },
  {
    id: 4,
    title: "Chicken Parmesan",
    description: "An incredible air frier recipe.",
    ingredients: ["Chicken", "Salt", "Black Pepper", "Eggs", "Flour", "Panko Breadcrumbs", "Parmesan Cheese", "Marinara Sauce", "Fresh Mozzarella Cheese", "Fresh Finely Chopped Parsley"],
  },
  {
    id: 5,
    title: "American Chop Suey",
    description: "",
    ingredients: [""],
  },
  {
    id: 6,
    title: "Steak and Cheese Subs",
    description: "",
    ingredients: ["Sliced Steak", "Cheese", "Sub Rolls"],
  },
  {
    id: 7,
    title: "Chicken Fajitas",
    description: "",
    ingredients: [""],
  },
  {
    id: 8,
    title: "Chicken Quesadillas",
    description: "",
    ingredients: [""],
  },
  {
    id: 9,
    title: "Chicken and Veggie Stir-fry",
    description: "",
    ingredients: ["Chicken Breast Cubed", "Salt", "Pepper", "Sliced Mushrooms", "Cooking Oil", "Minced Garlic", "Minced Ginger", "Sesame Oil", "Soy Sauce", "Brown Sugar", "Chicken Broth", "Flour"],
  },
  {
    id: 10,
    title: "BBQ Meatloaf and Veggies",
    description: "",
    ingredients: ["Ground Beef", "Large Egg", "Bread Crumbs", "BBQ Sauce", "Smoked Paprika", "Garlic Powder", "Salt", "Sweet Potato", "Broccoli", "Olive Oil", "Seasoning Salt", "Salt/Pepper to taste"],
  },
  {
    id: 11,
    title: "Steak and Cheese Stuffed Peppers",
    description: "",
    ingredients: ["Sliced Steak", "Cheese", "Bell Peppers"],
  },
  {
    id: 12,
    title: "Sausage Subs",
    description: "",
    ingredients: ["Spicy Sausages", "Cheese", "Sub Roll"],
  },
  {
    id: 13,
    title: "Pulled Chicken Sandwiches",
    description: "",
    ingredients: [""],
  },
  {
    id: 14,
    title: "Lasagna",
    description: "",
    ingredients: [""],
  },
  {
    id: 15,
    title: "Lemon Chicken",
    description: "",
    ingredients: [""],
  },
  {
    id: 16,
    title: "Homemade Pizza",
    description: "",
    ingredients: [""],
  },
  {
    id: 17,
    title: "Shepard's Pie",
    description: "",
    ingredients: [""],
  },
  {
    id: 18,
    title: "Pad Thai",
    description: "",
    ingredients: [""],
  },
  {
    id: 19,
    title: "Chicken Chimichanga",
    description: "",
    ingredients: [""],
  },
  {
    id: 20,
    title: "Chicken Burrito",
    description: "",
    ingredients: [""],
  },
  {
    id: 21,
    title: "Chili",
    description: "",
    ingredients: [""],
  },
  {
    id: 22,
    title: "Homemade BBQ Chicken Tenders",
    description: "Fantastic airfried homemade chicken tenders.",
    ingredients: ["Chicken Tenderloins", "BBQ Sauce", "Panko Bread Crumbs", "Broccoli(Side)", "Suddenly Salad(Pasta Salad)"],
  },
]

export const myReviews = [
  {
    id: 1,
    title: "Fantastic!",
    firstName: "First",
    lastName: "Last",
    comment: "Great",
    stars: 5,
    timestamp: "7 weeks ago"
  },
  {
    id: 2,
    title: "Awesome!",
    firstName: "Second",
    lastName: "Last",
    comment: "Fantastic service!",
    stars: 5,
    timestamp: "4 weeks ago"
  },
]

export const myItems = [
  {
    id: 1,
    name: "Computer",
    image: "./assets/tech_one.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 2,
    name: "Computer",
    image: "./assets/tech_two.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 3,
    name: "Computer",
    image: "./assets/tech_three.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 4,
    name: "Computer",
    image: "./assets/tech_four.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 5,
    name: "Computer",
    image: "./assets/tech_five.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 6,
    name: "Computer",
    image: "./assets/tech_six.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 7,
    name: "Computer",
    image: "./assets/tech_seven.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 8,
    name: "Computer",
    image: "./assets/tech_eight.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 9,
    name: "Computer",
    image: "./assets/tech_nine.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 10,
    name: "Computer",
    image: "./assets/tech_ten.jpg",
    description: "A powerful machine.",
    department: "Tech",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 1595.00,
    rating: 5,
    sale: false,
  },
  {
    id: 11,
    name: "Vitamins",
    image: "./assets/health_one.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 12,
    name: "Vitamins",
    image: "./assets/health_two.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 13,
    name: "Vitamins",
    image: "./assets/health_three.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 14,
    name: "Vitamins",
    image: "./assets/health_four.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 15,
    name: "Vitamins",
    image: "./assets/health_five.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 16,
    name: "Vitamins",
    image: "./assets/health_six.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 17,
    name: "Vitamins",
    image: "./assets/health_seven.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 18,
    name: "Vitamins",
    image: "./assets/health_eight.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 19,
    name: "Vitamins",
    image: "./assets/health_nine.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 20,
    name: "Vitamins",
    image: "./assets/health_ten.jpg",
    description: "Keep your body healthy.",
    department: "Health",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 9.99,
    rating: 5,
    sale: false,
  },
  {
    id: 21,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 22,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 23,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 24,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 25,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 26,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 27,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 28,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 29,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 30,
    name: "Paper Towels",
    image: "./assets/household_one.png",
    description: "Strong paper towels.",
    department: "Household Goods",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Paper",
    yearOfRelease: "0000",
    price: 6.50,
    rating: 5,
    sale: false,
  },
  {
    id: 31,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 32,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 33,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 34,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 35,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 36,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 37,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 38,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 39,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 40,
    name: "Couch",
    image: "./assets/furniture_one.jpg",
    description: "A massive, comfy couch.",
    department: "Furniture",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Leather",
    yearOfRelease: "0000",
    price: 400.00,
    rating: 5,
    sale: false,
  },
  {
    id: 41,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 42,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 43,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 44,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 45,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 46,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 47,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 48,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 49,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 50,
    name: "Shirt",
    image: "./assets/clothes_one.png",
    description: "A comfy shirt.",
    department: "Clothes",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "Cotton",
    yearOfRelease: "0000",
    price: 6.00,
    rating: 5,
    sale: false,
  },
  {
    id: 51,
    name: "Tent",
    image: "./assets/outdoors_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 52,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 53,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 54,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 55,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 56,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 57,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 58,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 59,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 60,
    name: "Tent",
    image: "./assets/tent_one.jpg",
    description: "A roomy tent.",
    department: "Outdoors",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 35.00,
    rating: 5,
    sale: false,
  },
  {
    id: 61,
    name: "Dog Food",
    image: "./assets/pets_one.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 62,
    name: "Dog Food",
    image: "./assets/pets_two.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 63,
    name: "Dog Food",
    image: "./assets/pets_three.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 64,
    name: "Dog Food",
    image: "./assets/pets_four.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 65,
    name: "Dog Food",
    image: "./assets/pets_five.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 66,
    name: "Dog Food",
    image: "./assets/pets_six.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 67,
    name: "Dog Food",
    image: "./assets/pets_seven.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 68,
    name: "Dog Food",
    image: "./assets/pets_eight.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 69,
    name: "Dog Food",
    image: "./assets/pets_nine.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 70,
    name: "Dog Food",
    image: "./assets/pets_ten.jpg",
    description: "Food your pet will love.",
    department: "Pets",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 20.00,
    rating: 5,
    sale: false,
  },
  {
    id: 71,
    name: "Apples",
    image: "./assets/food_one.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 72,
    name: "Apples",
    image: "./assets/food_two.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 73,
    name: "Apples",
    image: "./assets/food_three.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 74,
    name: "Apples",
    image: "./assets/food_four.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 75,
    name: "Apples",
    image: "./assets/food_five.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 76,
    name: "Apples",
    image: "./assets/food_six.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 77,
    name: "Apples",
    image: "./assets/food_seven.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 78,
    name: "Apples",
    image: "./assets/food_eight.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 79,
    name: "Apples",
    image: "./assets/food_nine.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
  {
    id: 80,
    name: "Apples",
    image: "./assets/food_ten.jpg",
    description: "A healthy snack.",
    department: "Food",
    subDepartment: "",
    brand: "",
    ageRange: "",
    material: "",
    yearOfRelease: "0000",
    price: 0.50,
    rating: 5,
    sale: false,
  },
]